config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  root 'pages#one'
  get 'pages/two'
  get 'pages/three'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>



    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>


  <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-inverse">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">The Second App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= pages_one_path%>">One</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= pages_two_path%>">Two</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= pages_three_path%>">Three</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>




  <%= yield %>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

  </body>
</html>

app/views/pages/one.html.erb
<h1>"Con tu nombre completo en la pagina de inicio" :)</h1>

app/views/pages/three.html.erb
<h2>Este es un titulo h2</h2>
<p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eum, temporibus quibusdam est quidem adipisci sunt rerum veniam dolore perferendis maiores aut vel nemo veritatis, velit nostrum quos laboriosam perspiciatis?
</p>

app/views/pages/two.html.erb
<h1>PANTALLAZO!</h1>
<br>
<hr>
Esta foto viene de la carpeta public
<br>
<img src="../pantallazo 2021-04-19 21-26-22.png" alt="No funciona">

<hr>
<br>
<hr>

Este de abajo viene del asset path
<br>
<%= image_tag "Screenshot from 2021-04-19 21-26-22.png" %>